algoritmo "ler as dimensões do triângulo"
// Função : ler base, altura e área do triângulo
// Autor : ariany
// Data : 15/03/2022
// Seção de Declarações 
var
base,altura,area: real
inicio
escreval ("Digite a base: ")
leia (base)
escreval ("Digite a altura: ")
leia (altura)
area <- base * altura/2
escreval ("A area do seu triângulo é de ", area)

// Seção de Comandos 
fimalgoritmo
