algoritmo "semnome"
// Função : Fibonacci
// Autor : Ariany Andrade
// Data : 06/09/2022
// Seção de Declarações 
var
numero, contador, anterior, posterior, resultado: inteiro
inicio
escreval ("Digite um número: ")
leia(numero)
   posterior <- 1
escreval(posterior)
 para contador de 1 ate numero faca
   resultado <- anterior + posterior
  escreval(resultado)
    anterior <- posterior
    posterior <- resultado
    resultado <- contador
 fimpara
fimalgoritmo
