algoritmo "CalculaMedia"
// Função : Calcular a média de 2 notas
// Autor : Ariany
// Data : 26/04/2022
// Seção de Declarações 
var
 P1,P2,MEDIA:real
inicio
// DADOS DE ENTRADA
escreval("Entre com um valor para P1: ")
leia(P1)
escreval("Entre com um valor para P2: ")
leia(P2)
//FIM DOS DADOS DE ENTRADA
//PROCESSAMENTO
MEDIA <- (P1+P2)/2
//FIM DO PROCESSAMENTO
//DADOS DE SAÍDA
escreval("A média do aluno é: ",MEDIA)
//FIM DOS DADOS DE SAÍDA

fimalgoritmo
