algoritmo "revisão/quadrado em asteriscos"
// Função : ler o tamanho do lado de um quadrado e imprime um quadrado daquele
//...tamanho com asteriscos
// Autor : Ariany Andrade
// Data : 20/09/2022
// Seção de Declarações 
var
x,quadrado,y:inteiro
inicio
// Seção de Comandos
escreval (" Digite o tamanho do quadrado: ")
leia(quadrado)
para x de 1 ate quadrado faca
  para y de 1 ate quadrado faca
   escreva("*")
  fimpara
  escreval()
fimpara


fimalgoritmo
