algoritmo "revisão/ímpar"
// Função : mostrar e somar todos os números ímpares de 1 até 200
// Autor : Ariany Andrade
// Data : 20/09/2022
// Seção de Declarações 
var
contador, soma: inteiro
inicio
// Seção de Comandos
para contador de 1 ate 200 faca
 se contador mod 2 <> 0 entao
 escreval(contador)
 soma <- soma + contador
 fimse
fimpara
escreval (" A soma de todos os números ímpares é: ",soma)


fimalgoritmo
