algoritmo "exercicio 03"
// Autor : Ariany Andrade
// Data : 06/09/2022
// Seção de Declarações 
var
numero, contador: inteiro
resultado: real

inicio
//Faça um programa que solicite um número inteiro e que faça:
//Ex: número digitado 5
//1/1 + 1/2 + 1/3 + 1/4 + 1/5 = 2,28

escreval ("Digite um número: ")
leia(numero)
 para contador de 1 ate numero faca
 resultado <- resultado + (1/contador)
 fimpara
escreval ("O resultado é: ",resultado)


fimalgoritmo
