algoritmo "tabuada"
// Função : fazer uma tabuada com o numero solicitado pelo usuario
// Autor : ariany andrade
// Data : 30/08/2022
// Seção de Declarações 
var
x, numero,resultado:inteiro
inicio
// Seção de Comandos 
escreval (" Digite um número: ")
leia(numero)
para x de 1 ate 10 faca
   resultado <- numero * x
   escreval(numero," *",x," = ",resultado)


fimpara

fimalgoritmo
