algoritmo "CalcularValorPeças"
// Função :
// Autor : ariany
// Data : 26/04/2022
// Seção de Declarações 
var
 VALOR,QTDE,VT:real
inicio
escreval("Digite o valor das peças: ")
leia(VALOR)
escreval("Digite a quantidade de peças: ")
leia(QTDE)
//FIM DOS DADOS DE ENTRADA
//PROCESSAMENTO
  VT <-(QTDE*VALOR)
// FIM DO PROCESSAMENTO
// DADOS DE SAÍDA
escreval(" O valor total de peças é: ",VT)
//FIM DOS DADOS DE SAÍDA
fimalgoritmo
